services:
  chat-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: chatdb 
      POSTGRES_USER: chatuser 
      POSTGRES_PASSWORD: chatpass
    ports:
      - 5222:5432
    volumes:
      - chat-db-data:/var/lib/postgresql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - chat-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://chat-db:5432/chatdb
      SPRING_DATASOURCE_USERNAME: chatuser 
      SPRING_DATASOURCE_PASSWORD: chatpass 
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

volumes:
  chat-db-data: